apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: mariadb
  name: mariadb
  labels:
    app: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
      tier: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: mariadb
        tier: backend
    spec:
      containers:
      - image: mariadb:10.6
        name: mariadb
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            cpu: "0.5"
            memory: "500Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: ro0tP4sSworD
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: wpuser
        - name: MYSQL_PASSWORD
          value: W0rd_Pr3sSUs3r.
        volumeMounts:
        - name: "mariadb-persistent-storage"
          mountPath: "/var/lib/mysql/"
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc
