name: Checkov

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  scan:
    permissions:
      contents: read
      security-events: write
      actions: read
      
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Checkov GitHub Action
        id: checkov
        uses: bridgecrewio/checkov-action@v12.2655.0
        with:
          output_format: sarif
          output_file_path: results.sarif
        continue-on-error: true
        
      - name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          name: checkov-results
          path: ${{ github.workspace }}/results.sarif

      - name: Close related pull requests
        if: success()
        run: |
          # Extract issue IDs from the SARIF file
          issue_ids=$(jq -r '.runs[].results[].locations[].physicalLocation.artifactLocation.uri' results.sarif | grep -oP '\d+$' | sort -u)
          
          # Close pull requests related to each issue
          for issue_id in $issue_ids; do
            # Fetch open pull requests related to the issue
            pr_numbers=$(gh pr list --state=open --label="security-issue-$issue_id" --json=number -q ".[] | .number")

            # Close each open pull request
            for pr_number in $pr_numbers; do
              gh pr close $pr_number --comment="This pull request is being closed because the related security issue has been fixed."
            done
          done
